### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ghost** [daitan/Granblue-DPS-Meter#1]
Hi,

I am very interested in this tool which could examine the best gears composition by real test instead of calculation or  simulation.

However, I cannot understand how to use this tool. Could you please describe in README.md? 

Many thanks,
hajime

**Comment by daitan** [comment]
It's a chrome extension, I haven't had too much time to work and expand on this. It's just a barebones meter currently.

https://chrome.google.com/webstore/detail/blpjaomohincbonfemfihdabmfoglhpb
